### ISSUE TITLE
Update benchmarks

### ISSUE THREAD

**Issue by blakeembrey** [jonschlinkert/arr-flatten#1]
Hey! I just found this and you're right about the depth argument. I did a bit of testing before this and found it wasn't quite that big of a slowdown, but the `array-flatten` is faster without it so I implemented a shorter code path for when it's undefined. That changed the benchmark here somewhat.

```
#1: large 
  current x 426,603 ops/sec ±2.21% (88 runs sampled)
  lib-array-flatten x 427,445 ops/sec ±2.76% (90 runs sampled)

  fastest is lib-array-flatten
#2: medium 
  current x 1,860,941 ops/sec ±1.41% (88 runs sampled)
  lib-array-flatten x 1,753,099 ops/sec ±2.32% (88 runs sampled)

  fastest is current
#3: small 
  current x 5,005,209 ops/sec ±1.36% (86 runs sampled)
  lib-array-flatten x 5,473,100 ops/sec ±2.77% (89 runs sampled)

  fastest is lib-array-flatten
```

Run with `iojs@2.0.1`. The benchmark tends to frequently switch between `current` or `lib-array-flatten`.

**Comment by jonschlinkert** [comment]
this is why I love programming!  awesome, I'll update them as soon as I get a chance. thanks!

**Comment by jonschlinkert** [comment]
oh, and to clarify, I meant the fact that other developers just care about code quality and want to share better ways of doing things is pretty great. thanks again
